### ISSUE TITLE
Dicebear API for initials avatars has changed

### ISSUE THREAD

**Issue by aremesal** [balajidharma/laravel-vue-admin-panel#32]
Be aware that since the Dicebear API for creating initials avatars has changed, it's not working anymore.

I've fixed it with the new API call and sent a [pull request](https://github.com/balajidharma/laravel-vue-admin-panel/pull/31) already.

API description from Dicebear: [https://www.dicebear.com/styles/initials/](https://www.dicebear.com/styles/initials/)

**Comment by balajidharma** [comment]
https://github.com/balajidharma/laravel-vue-admin-panel/pull/31
