### ISSUE TITLE
undefined property after build

### ISSUE THREAD

**Issue by ghost** [balajidharma/laravel-vue-admin-panel#4]
Hi, I trying to serve the repo with `php artisan serve` without docker. But I found there have errors when click `Submit` button at all the page

I ran npm run build to compile the assets  then just type `php artisan serve`.
![image](https://user-images.githubusercontent.com/37526525/192685845-fa5bee15-7efe-4bec-a717-14e0cc2fa177.png)

If I ran `npm run dev` then have no error.
@balajidharma

**Comment by ghost** [comment]
@balajidharma 
I have fixed in my local with some issue I found so far.

First Issue
Update Role & Update User (undefines property error after build)
Sample Update Role (also apply in Update User)

Fixed
I created a submit function then applied in form then problem resolved.
![image](https://user-images.githubusercontent.com/37526525/192724510-e810b746-38d2-4daf-a786-f50c13b08049.png)

Second Issue
Create Role & Create User page checkbox auto ticked all bugs
The checkbox will tick all permissions when I tick 1 of the checkbox button. And the value I debug is true and false. (It should be array)

Fixed
Change default string value to array
![image](https://user-images.githubusercontent.com/37526525/192725537-cc814386-9ada-4332-ab10-bac05ac82532.png)
![image](https://user-images.githubusercontent.com/37526525/192725615-84ff3969-0421-4cae-a2db-e9ad53b7cdc4.png)

**Comment by balajidharma** [comment]
@JustonJ99 thank you for reporting the issue.

I am able to replicate the second issue and fixed that issue. But Unable to replicate the first issue.
