### ISSUE TITLE
error on instalation using composer

### ISSUE THREAD

**Issue by pakuningratan** [balajidharma/laravel-vue-admin-panel#46]
error on instalation using composer

  Access to undeclared static property Spatie\Permission\PermissionRegistrar::$pivotPermission
  at database\migrations\2022_07_11_225131_create_permission_tables.php:54
  
<img width="916" alt="image" src="https://github.com/balajidharma/laravel-vue-admin-panel/assets/68019361/08bb55f8-6b92-4903-bf40-1341c5beae51">

**Comment by balajidharma** [comment]
I have re-published Spatie migration. Try with a new installation.
