### ISSUE TITLE
Error on update after production build

### ISSUE THREAD

**Issue by emtiazzahid** [balajidharma/laravel-vue-admin-panel#5]
Step to produce:
run ``` npm run build ```

Goto : permissons or role or users list > edit > press update > check console
```
TypeError: Cannot read properties of undefined (reading 'permission')
```
Node version: v16.14.2
NPM version: 8.5.0

**Comment by ghost** [comment]
You could try this. https://github.com/balajidharma/laravel-vue-admin-panel/issues/4#issue-1388696464

**Comment by emtiazzahid** [comment]
> You could try this. [#4 (comment)](https://github.com/balajidharma/laravel-vue-admin-panel/issues/4#issue-1388696464)

added an [PR ](https://github.com/balajidharma/laravel-vue-admin-panel/pull/6) for that

**Comment by balajidharma** [comment]
Thank you @emtiazzahid & @JustonJ99
