### ISSUE TITLE
A `admin_tag` category type not exists.

### ISSUE THREAD

**Issue by dmb-220** [balajidharma/laravel-vue-admin-panel#67]
public function update(MenuItemUpdateData $data, Menu $menu, MenuItem $item, MenuItemUpdateAction $menuItemUpdateAction)

    {

        $this->authorize('adminUpdate', $item);

        **$menuItemUpdateAction->handle($data, $item);**

        return redirect()->route('admin.menu.item.index', $menu->id)

            ->with('message', 'Menu Item updated successfully.');

    } when create new menu or update get error
new version update get problem

**Comment by balajidharma** [comment]
The starter kit not supporting updates. Because doing active developments.

Try new installation or drop all the tables and force publish vendor.  After run the migration with seeder

`php artisan vendor:publish --tag=admin-core  --force`

`php artisan migrate --seed --seeder=AdminCoreSeeder`
